# Generated by Django 4.1.3 on 2023-07-16 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet1032", "0006_alter_article_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
