# Generated by Django 4.1.3 on 2023-07-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet1032", "0007_alter_article_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(null=True),
        ),
    ]
