# Generated by Django 4.1.3 on 2023-07-16 00:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planet1032", "0010_alter_article_pub_date_alter_article_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="user",
        ),
        migrations.CreateModel(
            name="Graphics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("graphic_file", models.ImageField(upload_to="graphic_file/")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("E", "educational article"),
                            ("F", "Fiction"),
                            ("G", "Graphics"),
                            ("O", "Other"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(default=datetime.datetime.now, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
