# Generated by Django 4.1.3 on 2023-07-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet1032", "0012_article_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(default=""),
        ),
    ]
