# Generated by Django 4.1.3 on 2023-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet1032", "0015_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[("E", "科普"), ("F", "小说"), ("G", "漫画/图像"), ("O", "其他")],
                default="O",
                max_length=1,
            ),
        ),
    ]
