# Generated by Django 4.1.3 on 2023-07-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet1032", "0016_image_is_deleted_alter_article_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "男"), ("F", "女"), ("N", "不愿透露"), ("O", "其他")],
                default="O",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nature",
            field=models.CharField(
                choices=[("M", "男"), ("F", "女"), ("N", "不愿透露"), ("O", "其他")],
                default="N",
                max_length=1,
            ),
        ),
    ]
