# Generated by Django 4.1.3 on 2023-07-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet1032", "0017_alter_userprofile_gender_alter_userprofile_nature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nature",
            field=models.CharField(
                choices=[("Z", "主"), ("B", "贝"), ("W", "双"), ("N", "不愿透露")],
                default="N",
                max_length=1,
            ),
        ),
    ]
