# Generated by Django 4.1.3 on 2023-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet1032", "0021_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favourite_article",
            field=models.ManyToManyField(
                related_name="favorited_by", to="planet1032.article"
            ),
        ),
    ]
