# Generated by Django 4.1.3 on 2023-07-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet1032", "0023_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dislike_article",
            field=models.ManyToManyField(
                related_name="disliked_by", to="planet1032.article"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="like_article",
            field=models.ManyToManyField(
                related_name="liked_by", to="planet1032.article"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="report_article",
            field=models.ManyToManyField(
                related_name="reported_by", to="planet1032.article"
            ),
        ),
    ]
